### ISSUE TITLE
[BUG] Trimmed videos not playing back correctly in iOS

### ISSUE THREAD

**Issue by jaysignorello** [CaiJingLong/flutter_photo_manager#582] opened 2021-08-11 19:16 UTC
**Describe the bug**
When a user has previously edited a video and it's played back in flutter, the video is shifted to the right and almost entirely cut off from the screen (even if played in full screen) when using this library to pull the video.

This only seems to happen with videos taken in portrait mode, not landscape. I'm currently using the most recent release (1.3.1) of this library, as well as the most up-to-date version of video_player (2.1.12).

`asset.getMediaUrl()` and `asset.file` both return videos with the same issue. However, `asset.originFile` works fine, given it's pulling the original version of the file.

**To Reproduce**
1. Create a normal Portrait video on real Apple device
2. Edit the video and trim some from the beginning
3. Load and playback the video

**Flutter version**
```
Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-x64, locale en-US)
    • Flutter version 2.2.3 at /usr/local/Caskroom/flutter/latest/flutter
    • Framework revision f4abaa0735 (6 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1
```

**Smartphone (please complete the following information):**
 - Device: iPhone 7 & iPhone X
 - OS: 14.6
 - Version 1.3.1

**Comment by AlexV525** [comment] 2021-08-18 11:54
Do you have any screenrecords for this?

**Comment by jaysignorello** [comment] 2021-08-22 19:38
@AlexV525 I didn't at the time, but I will this week.

**Comment by jaysignorello** [comment] 2021-08-31 14:41
@AlexV525 Attached is a screen recording in a demo, the demo app source code, and also a screenshot in fullscreen mode.

https://github.com/jaysignorello/flutter_photo_manager-issue-582

https://user-images.githubusercontent.com/213331/131523221-b474f482-0dc9-4c0e-be9f-708bd69a1452.MP4

![IMG_0214](https://user-images.githubusercontent.com/213331/131523232-c0511b5e-a821-4652-9f2e-6b6ad0f13bee.PNG)

**Comment by AlexV525** [comment] 2021-09-02 09:49
Took a glance of this issue, and it seems to be a chewie issue rather than this plugin. Will provide more feedback after I tried your sample.

**Comment by AlexV525** [comment] 2021-09-02 10:03
Please take a look at https://github.com/fluttercandies/flutter_wechat_assets_picker/blob/master/lib/src/widget/builder/video_page_builder.dart for how to implement a video player with the correct aspect ratio. The aspect ratio calculation is not recommended for a video since the controller will decode the real one after it got initialized.

<details>
<summary>Code sample</summary>

```dart
class _MyHomePageState extends State<MyHomePage> {
  late final AssetEntity assetInFocus;

  late final VideoPlayerController _controller;

  /// Whether the controller has initialized.
  bool hasLoaded = false;

  /// Whether there's any error when initialize the video controller.
  bool hasErrorWhenInitializing = false;

  @override
  void initState() {
    super.initState();
    _load();
  }

  Future<void> _load() async {
    PermissionState state = await PhotoManager.requestPermissionExtend();

    if (PermissionState.authorized == state) {
      List<AssetPathEntity> assetPaths = await PhotoManager.getAssetPathList(
        type: RequestType.video,
      );

      AssetPathEntity recent =
          assetPaths.firstWhere((e) => (e.name == 'Recents'));

      List<AssetEntity> assets = await recent.getAssetListPaged(0, 100);

      if (assets.isNotEmpty) {
        assetInFocus = assets.first;
        initializeVideoPlayerController();
      }
      setState(() {});
    }
  }

  /// Get media url from the asset, then initialize the controller.
  Future<void> initializeVideoPlayerController() async {
    final String? url = await assetInFocus!.getMediaUrl();
    if (url == null) {
      hasErrorWhenInitializing = true;
      if (mounted) {
        setState(() {});
      }
      return;
    }
    _controller = VideoPlayerController.network(Uri.parse(url).toString());
    try {
      await _controller.initialize();
      hasLoaded = true;
    } catch (e) {
      hasErrorWhenInitializing = true;
    } finally {
      if (mounted) {
        setState(() {});
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: hasLoaded
            ? FutureBuilder(
                future: assetInFocus.getMediaUrl(),
                builder: (BuildContext context, AsyncSnapshot s) {
                  if (!s.hasData)
                    return Center(
                      child: CircularProgressIndicator(),
                    );

                  if (s.data == null)
                    return Center(
                      child: Text('ooops'),
                    );

                  return AspectRatio(
                    aspectRatio: _controller.value.aspectRatio,
                    child: VideoPlayer(_controller),
                  );
                },
              )
            : Text('Still loading'),
      ),
    );
  }
}
```
</details>

**Comment by AlexV525** [comment] 2021-09-02 10:09
For chewie:

![image](https://user-images.githubusercontent.com/15884415/131825635-7364a5ae-e23c-4944-babd-5762a0775576.png)

<details>
<summary>Code sample</summary>

```dart
class _MyHomePageState extends State<MyHomePage> {
  late final AssetEntity assetInFocus;

  late final ChewieController _controller;

  /// Whether the controller has initialized.
  bool hasLoaded = false;

  /// Whether there's any error when initialize the video controller.
  bool hasErrorWhenInitializing = false;

  @override
  void initState() {
    super.initState();
    _load();
  }

  Future<void> _load() async {
    PermissionState state = await PhotoManager.requestPermissionExtend();

    if (PermissionState.authorized == state) {
      List<AssetPathEntity> assetPaths = await PhotoManager.getAssetPathList(
        type: RequestType.video,
      );

      AssetPathEntity recent =
          assetPaths.firstWhere((e) => (e.name == 'Recents'));

      List<AssetEntity> assets = await recent.getAssetListPaged(0, 100);

      if (assets.isNotEmpty) {
        assetInFocus = assets.first;
        initializeVideoPlayerController();
      }
      setState(() {});
    }
  }

  /// Get media url from the asset, then initialize the controller.
  Future<void> initializeVideoPlayerController() async {
    final String? url = await assetInFocus.getMediaUrl();
    if (url == null) {
      hasErrorWhenInitializing = true;
      if (mounted) {
        setState(() {});
      }
      return;
    }
    final VideoPlayerController _vc = VideoPlayerController.network(
      Uri.parse(url).toString(),
    );
    _controller = ChewieController(videoPlayerController: _vc);
    try {
      hasLoaded = true;
    } catch (e) {
      hasErrorWhenInitializing = true;
    } finally {
      if (mounted) {
        setState(() {});
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: hasLoaded
            ? FutureBuilder(
                future: assetInFocus.getMediaUrl(),
                builder: (BuildContext context, AsyncSnapshot s) {
                  if (!s.hasData)
                    return Center(
                      child: CircularProgressIndicator(),
                    );

                  if (s.data == null)
                    return Center(
                      child: Text('ooops'),
                    );

                  return Chewie(controller: _controller);
                },
              )
            : Text('Still loading'),
      ),
    );
  }
}
```
</details>

**Comment by AlexV525** [comment] 2021-09-02 14:10
I can't repro this on iPhone 12 with a trimmed video (as the screenshot before) with iOS 14.7.1, and I'm not sure how to repro this too.

**Comment by jaysignorello** [comment] 2021-09-02 23:55
@AlexV525 I've been able to reproduce it on an iPhone 12 Mini, iPhone X, and iPhone 7. Attached is the iPhone 12 Mini screen video of the issue. 

I exported the video, including all the metadata from the phone. Loaded it up on the simulator and was indeed able to get to reproduce this on an iPhone 11 Pro simulator. 

Here is a link to the edit version of the file you can download and test out. As you'll see, it plays fine in Apple Photos, but not in the demo app.

https://drive.google.com/file/d/1QBn3VS80mq9utJ4OuBY8HOen3choW8LF/view?usp=sharing

Now the following link is the unedited version. This one plays completely fine on all devices and simulator.

https://drive.google.com/file/d/1yvAhkT6dgneI8OjmyFIK1S-kQ5eoSirj/view?usp=sharing

**Comment by AlexV525** [comment] 2021-09-09 14:27
I haven't have spare time to investigate. If you're able to debug some native code with iOS, please do so.

**Comment by AlexV525** [comment] 2021-09-15 05:52
I was able to reproduce this on simulator with iOS 14.5, but there is a difference with your description, which the `originalFile` is failed to play the video with the correct position too.
![image](https://user-images.githubusercontent.com/15884415/133378053-f8e35857-1806-4350-8d54-64fc011ee34c.png)

**Comment by AlexV525** [comment] 2021-09-15 06:52
As I investigate with this issue, it turns out the video data didn't get interrupted, but the player did. I switched the player to ijkplayer and the video's preview size is correct (though the preview might be a little strange). So the conclusion is this would a `video_plugin` issue.

![image](https://user-images.githubusercontent.com/15884415/133384735-7c92626c-f750-44a1-9a23-8f0eb74af411.png)

Closing this, and please file issues for the `video_player` plugin.

**Closed by AlexV525** 2021-09-15 06:52 UTC
Labels: ios, video, photo library, have use case
