### ISSUE TITLE
[BUG] deleteWithIds not working

### ISSUE THREAD

**Issue by Adnanbd** [CaiJingLong/flutter_photo_manager#336] opened 2020-07-18 12:53 UTC
**Describe the bug**
I can not delete any photo

**Expected behavior**

**Screenshots**

**Flutter version**

Channel beta, 1.19.0-4.3.pre

**Smartphone (please complete the following information):**
 - Device: Oneplus 6

```bash

```

**Comment by leonardocustodio** [comment] 2020-09-10 06:13
Duplicate of #362

**Closed** 2021-06-01 14:51 UTC
