### ISSUE TITLE
[Feature] Android support for MediaStore.Downloads

### ISSUE THREAD

**Issue by krokyze** [CaiJingLong/flutter_photo_manager#313] opened 2020-06-13 19:13 UTC
Not critical, but it would be nice to be able to read media from [MediaStore.Downloads](https://developer.android.com/reference/android/provider/MediaStore.Downloads) too. Thanks 😉

**Comment by momoDragon** [comment] 2021-05-31 07:17
any update on this feature? i want to be able to get images from downloads folder

**Comment by AlexV525** [comment] 2021-05-31 07:33
Please provide the version of the package that you're using. And:
![IMG_20210531_153303](https://user-images.githubusercontent.com/15884415/120157349-85d77300-c225-11eb-8630-c1ade837fd56.jpg)

**Comment by momoDragon** [comment] 2021-05-31 07:38
photo_manager: ^1.2.1

I am using AVD emulator with API 30, Android 11.1
Images from here are not showing up
<img width="467" alt="Screenshot 2021-05-31 at 3 35 59 PM" src="https://user-images.githubusercontent.com/40727575/120157783-f2eb0880-c225-11eb-9210-20f1bfc12e05.png">

These are the directories it was able to detect which have images
<img width="144" alt="Screenshot 2021-05-31 at 3 37 05 PM" src="https://user-images.githubusercontent.com/40727575/120157959-2a59b500-c226-11eb-9ff8-78af52ea2d63.png">

Unable to detect images from downloads even on the example project and also my own project

**Comment by AlexV525** [comment] 2021-05-31 08:06
Just created a new simulator and the Download folder exist and displayed.
![image](https://user-images.githubusercontent.com/15884415/120161681-2c257780-c22a-11eb-8720-dff1321562fc.png)
![image](https://user-images.githubusercontent.com/15884415/120161620-19ab3e00-c22a-11eb-971e-0aade56a5624.png)
![image](https://user-images.githubusercontent.com/15884415/120161655-2465d300-c22a-11eb-8a17-79245d69bd2d.png)

**Comment by AlexV525** [comment] 2021-06-01 14:52
So AFAICT this is a device/entity specific issue. Closing.

**Closed by AlexV525** 2021-06-01 14:52 UTC
Labels: android, invalid, more info

**Comment by alex-myznikov** [comment] 2021-07-20 13:54
The same as in @momoDragon's case I've been able to get images on simulator from Recent and Pictures, but not from the Downloads.

Android 11.0 API 30
photo_manager 1.2.2

Code I used to get the albums:
`PhotoManager.getAssetPathList(
    onlyAll: true,
    type: RequestType.image
)`

@AlexV525 Can you give us a link to the app code you've used for testing this issue?

**Comment by AlexV525** [comment] 2021-07-20 14:02
> @AlexV525 Can you give us a link to the app code you used for testing this issue?

I'm using the example to test.

**Comment by alex-myznikov** [comment] 2021-07-20 15:30
So, yeah, I've tested the example on the same simulator as described above and got only Recent and Pictures, but not Downloads. Though I have pictures in that directory as well.

![Screenshot_1626791607](https://user-images.githubusercontent.com/26327708/126348057-87a8f343-4ff5-490a-b33f-de6937303431.png)


I think this is because the [MediaStore.Downloads](https://developer.android.com/reference/android/provider/MediaStore.Downloads) table (mentioned by @krokyze) is not in the `selections` yet, as it follows from the plugin's code:

`val selection =
            "${MediaStore.Images.Media.BUCKET_ID} IS NOT NULL $typeSelection $dateSelection $sizeWhere) GROUP BY (${MediaStore.Images.Media.BUCKET_ID}"`

According to this [link](https://developer.android.com/training/data-storage/shared/media) it looks like it has to be there for Android 10+ to get files from the Downloads:
<img width="856" alt="Screenshot 2021-07-20 at 18 14 12" src="https://user-images.githubusercontent.com/26327708/126349492-f637e1fd-b42e-49d9-83f5-e33f26fa7670.png">

These are just my 2 cents for this issue. Can not do more because I'm not an Android dev. Hope it will help...

**Comment by AlexV525** [comment] 2021-07-20 15:43
So now this issue become an environmental issue. How did you add your files into the `Downloads` folder? I simply drag all images to the emulator then let it import them.

**Comment by AlexV525** [comment] 2021-07-20 15:48
Also can you try with the latest version (1.2.7)?

**Comment by alex-myznikov** [comment] 2021-07-20 18:59
Yes, the same as you, I just dragged my images onto it. And yes, I've tried with 1.2.7.

**Comment by AlexV525** [comment] 2021-07-21 00:03
> Yes, the same as you, I just dragged my images onto it. And yes, I've tried with 1.2.7.

If you're using drag, you can check whether those images are showing in the photo app. Once they appear, the download folder should be appear too. If they don't, try a reboot first.

**Comment by alex-myznikov** [comment] 2021-07-21 15:42
> If you're using drag, you can check whether those images are showing in the photo app. Once they appeared, the download folder should appeared too. If they don't, try a reboot first.

I've tried what you suggested. 

Images sent to the simulator are instantly available in the Downloads directory through the Files app. But Google Photos app seems to not refetch data from Downloads until reboot. So finally after reboot it started working as expected.

Thank you for assistance. I think I need to conduct more testing on real devices. The solution with 'rebooting' doesn't look promising for the end-user experience. But it may work in a different way on real devices.

**Comment by AlexV525** [comment] 2021-07-21 15:46
> Thank you for assistance. I think I need to conduct more testing on real devices. The solution with 'rebooting' doesn't look promising for the end-user experience. But it may work in a different way on real devices.

That is somehow related to MediaStore scanning, it's not triggered instantly as users might expected, and can only be triggered *randomly*, which is why you can see there is a menu named `PhotoScanner` in the Photos app.

**Comment by alex-myznikov** [comment] 2021-07-21 16:20
Ok, thank you for the explanation! But anyway do you think if selecting from the [MediaStore.Downloads](https://developer.android.com/reference/android/provider/MediaStore.Downloads) table in addition to the MediaStore.Images can have a chance to solve this issue?

**Comment by AlexV525** [comment] 2021-07-21 16:29
> But anyway do you think if selecting from the [MediaStore.Downloads](https://developer.android.com/reference/android/provider/MediaStore.Downloads) table in addition to the MediaStore.Images can have a chance to solve this issue?

The root cause is the scanning, as I mentioned before. So I don't think that targeting the Downloads would help. Maybe this time it happens with the Downloads, but next time with other albums/folders.
