### ISSUE TITLE
entity.file not return when first time

### ISSUE THREAD

**Issue by sxd1140** [CaiJingLong/flutter_photo_manager#411] opened 2020-12-11 09:34 UTC
**Describe the bug**
`await entity.file` not return when first time but `originFile` had content.
Same image second time `file` had content.

Another image is same situation.

**Flutter version**
Flutter (Channel stable, 1.22.4, on macOS 11.0.1 20B29 darwin-x64, locale zh-Hans-CN)

**Smartphone (please complete the following information):**
 - Device: iPhoneXR
 - OS: iOS14

v0.5.8

**Comment by CaiJingLong** [comment] 2020-12-18 08:59
If this method does not throw an exception, it should always contain content. 
You need to provide a more complete reproduction to illustrate the steps you took to encounter this problem.

**Comment by sxd1140** [comment] 2020-12-21 06:01
Seem those image on icloud #359

**Comment by jaysignorello** [comment] 2021-07-07 00:28
@CaiJingLong @AlexV525 I'm having the same issue for video files only.

I've tried 

```
File file  = await entity.file;
```

and 

```
  PMProgressHandler handler = PMProgressHandler();
  handler.stream.listen((event) {
    print(
        'loading $asset => ${event.progress}, ${event.state} -- ${DateTime.now().millisecondsSinceEpoch}');
  });
  File file = asset.loadFile(isOrigin: false, progressHandler: handler);
```

Both result in a `File` object being returned instantly, but with fileSize = 0. After further testing, I believe it's downloading the video file from iCloud, as if you wait long enough and then reload the file, it works. This makes sense since `fetchFullSizeImageFile` method is configuring `PHImageRequestOptions` to be synchronous. Video doesn't have that same option, however, the progress handler doesn't seem to be working properly. 

I'm not entirely sure what the exact problem is, but I'd be happy to help collaborate on getting it fixed. Let me know how I can help.

**Comment by AlexV525** [comment] 2021-07-07 01:38
We're currently scheduled to refactored the iCloud part, and will cost maybe 1 or 2 months for it. Let us know if you have any ideas in how to implement the whole iCloud feature in a more proper way.

**Comment by jaysignorello** [comment] 2021-07-19 21:08
@AlexV525  #558 has made pulling the file successful now. I haven't been able to test it heavily with iCloud (#377), but so far looks like that is fixed as well.

The progress handler is still not 100% working however. It reports back `prepare` and `success` states, but never `loading`, even when a file takes many seconds to load. Added an issue #565

In terms of suggestions for iCloud feature or iOS in general, here are a few.

1. Move the project over to Swift (or at least the more complicated areas). I believe this will allow more developers (such as myself) contribute to bug fixes and feature improvements.

2. While iOS and Android share some similarities in terms of their APIs, they depart pretty quickly when it comes to some newer features (Live Photos, Slow-Mo videos,  etc). To provide a user experience that iOS users expect, more API features need to be supported in this library. 

For example, it'd be difficult to add LivePhoto support into this library since `AssetEntity` is limited to fetching one file, were as a LivePhoto is actually a Photo and Video file. The library API interface needs to support these differences, but not be overly complicated.

  Two possible solutions:
   1. Inheritance
   ```
     AssetEntityiOS asset = AssetEntityiOS.fromId(id);



```
AssetEntity asset = AssetEntity.fromId(id);
asset.iOS.isLivePhoto
asset.iOS.livePhotoKey
``` 

3. Expose  `PHVideoRequestOptions`, `AVAssetExportSession` settings similar to how image thumbnail creation has `ThumbOption`. There are times when quality matters and other times speed is preferred.

**Comment by AlexV525** [comment] 2021-07-20 01:38
> @AlexV525 #558 has made pulling the file successful now.

Sounds good, closing this issue.

> Move the project over to Swift (or at least the more complicated areas)

No matter we refactored in which language, it'll be a huge work. I personally have no experience in Objective-C, but I would recommend to refactor after these critical issues been resolved.

About Live Photos and other more specific issues, we'll track them separately.

**Closed by AlexV525** 2021-07-20 01:38 UTC
Labels: icloud, photo library

**Comment by MagTuxGit** [comment] 2021-08-03 12:48
1.2.8, iCloud photos still hangs
