### ISSUE TITLE
[Custom] lazy load getImageAsset

### ISSUE THREAD

**Issue by Shtibel** [CaiJingLong/flutter_photo_manager#72] opened 2019-05-28 19:52 UTC
When I call getImageAsset it takes 3 minutes to get a result from my device.
I have lots of images there...
How can I make it work faster?
Some kind of lazy loading the assets or a function that just gets the album name without the images.

And also when i click on the album I want to get the images by chunks not awate to get all of them.

How can I do that ?

Thank you!

**Comment by CaiJingLong** [comment] 2019-06-10 03:20
I don't know why you encounter such a problem. 
Because the API for reading photos is provided by the android/iOS sdk, and
my device iOS/android has thousands of pictures, and the loading speed will not exceed 3 seconds.

**Comment by Shtibel** [comment] 2019-06-14 15:52
Hi @CaiJingLong 
See this video and look how long it takes to get the images (about 30 seconds)

![ezgif-4-7f34df934993](https://user-images.githubusercontent.com/24429607/59521598-5793e800-8ed5-11e9-88aa-9bfcd84a0bd4.gif)

That is why I think it will be a good idea to get the images by chunks.
I got this idea from the cordova-plugin-photo-library.
See there explanation:
https://github.com/terikon/cordova-plugin-photo-library#chunked-output

What do you think?

**Comment by CaiJingLong** [comment] 2019-06-16 15:41
This problem has always existed, and many people have given feedback, but I don't know how to fix it.

Unless it can be reproduced on my device.

---

It may take a long time. I may need to completely refactor the underlying code to see if paging can be used to solve this problem.

**Comment by korenzerah** [comment] 2019-06-29 17:28
Hi,
It takes ~20 seconds for me also. 
Would appreciate improving performance, it's a great library.

**Comment by CaiJingLong** [comment] 2019-09-03 09:22
#94 can resolve the problem.
I will close this issue after uploading the next version.

**Comment by CaiJingLong** [comment] 2019-09-14 02:41
Update version to 0.4.1.

**Closed** 2019-09-14 02:40 UTC
Labels: merged
