### ISSUE TITLE
Panorama folder is showing in place of Recent in iPhone

### ISSUE THREAD

**Issue by nayanbabariya95** [CaiJingLong/flutter_photo_manager#524] opened 2021-06-14 19:12 UTC
If iPhone has the images in Panorama folder then Panorama folder is showing in place of Recent.

```
final assetPathEntities = await PhotoManager.getAssetPathList(type: RequestType.common);
print(assetPathEntities[0].name);
```
It will print "Panorama"

**Comment by TykanN** [comment] 2021-06-24 07:05
I reproduced same issue!

**Comment by TykanN** [comment] 2021-06-25 09:37
@nayanbabariya95
I solved problem using List.sort method.
`
final List<AssetPathEntity> assetPathEntities = await PhotoManager.getAssetPathList(type: RequestType.common);
assetPathEntities.sort((folder1, folder2){
   if(folder1.isAll) return -1;
   if(folder2.isAll) return 1;
   return 0;
});
`
Then, 'Recent' album is the first index of List.
Try it!

**Comment by AlexV525** [comment] 2021-06-28 15:55
Another sort path delegate takes here: https://github.com/fluttercandies/flutter_wechat_assets_picker/blob/master/lib/src/delegates/sort_path_delegate.dart

Closing since we have a valid solution.

**Closed by AlexV525** 2021-06-28 15:55 UTC
